#pragma once
// ─────────────────────────────────────────────────────────────────────────────
//  Nexus Kernel — convenience umbrella header
// ─────────────────────────────────────────────────────────────────────────────
#include <nexus/gfx/Types.h>
#include <nexus/gfx/Device.h>
#include <nexus/gfx/CommandBuffer.h>
#include <nexus/gfx/Swapchain.h>
#include <nexus/gfx/Allocator.h>
#include <nexus/gfx/RenderContext.h>
#include <nexus/animation/AnimationCore.h>
#include <nexus/geometry/Mesh.h>
#include <nexus/geometry/GeometryKernel.h>
#include <nexus/geometry/BooleanOperation.h>
#include <nexus/geometry/BevelChamfer.h>
#include <nexus/geometry/RemeshOperation.h>
#include <nexus/geometry/MeshDiagnosticOverlay.h>
#include <nexus/geometry/MeshIO.h>
#include <nexus/geometry/ExtrudeOperation.h>
#include <nexus/geometry/InsetFacesOperation.h>
#include <nexus/asset/SceneAsset.h>
#include <nexus/render/Camera.h>
#include <nexus/render/SceneGraph.h>
#include <nexus/render/Renderer.h>
#include <nexus/parametric/ConstraintGraph.h>
#include <nexus/parametric/ParametricSolver.h>
#include <nexus/parametric/ParametricSerialization.h>
#include <nexus/parametric/ParametricSamples.h>
#include <nexus/neural/NeuralRenderer.h>
