// ─── nx-factory generate endpoint — Generate route handler, validation, test stubs ──

import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

export interface GenerateEndpointOptions {
  app?: string | undefined;
  method?: string | undefined;
  path?: string | undefined;
}

function toCamelCase(str: string): string {
  return str.replace(/[-_]([a-z])/g, (_m, c: string) => c.toUpperCase());
}

function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return (camel[0]?.toUpperCase() ?? "") + camel.slice(1);
}

export async function generateEndpoint(
  name: string,
  options: GenerateEndpointOptions = {},
): Promise<void> {
  // Find the monorepo root
  let root = process.cwd();
  while (!(existsSync(join(root, "apps")) && existsSync(join(root, "packages"))) && root !== "/") {
    root = dirname(root);
  }

  if (!existsSync(join(root, "apps")) || !existsSync(join(root, "packages"))) {
    process.stderr.write(
      "Error: could not find monorepo root (need apps/ and packages/ directories).\n",
    );
    process.exit(1);
  }

  // Find the target app
  let appName = options.app;
  if (!appName) {
    // Try to detect from cwd
    const cwd = process.cwd();
    const appsDir = join(root, "apps");
    if (cwd.startsWith(appsDir)) {
      const relative = cwd.slice(appsDir.length + 1);
      appName = relative.split("/")[0] ?? undefined;
    }
  }

  if (!appName) {
    process.stderr.write(
      "Error: could not determine target app. Use --app <app-name> or run from inside an app directory.\n",
    );
    process.exit(1);
  }

  const appDir = join(root, "apps", appName);
  if (!existsSync(appDir)) {
    process.stderr.write(`Error: app directory not found: ${appDir}\n`);
    process.exit(1);
  }

  const method = options.method ?? "POST";
  const routePath = options.path ?? `/api/v1/${appName.replace("nexus-", "")}/${name}`;

  const handlerName = toCamelCase(name);
  const validatorName = `validate${toPascalCase(name)}Payload`;

  // ── Generate the route handler snippet ───────────────────────────────────

  const routeSnippet = `
// ── ${method} ${routePath} ─────────────────────────────────────────${"─".repeat(Math.max(0, 40 - routePath.length))}

function ${validatorName}(payload: unknown): ValidationResult {
  if (!payload || typeof payload !== "object") return "payload must be a JSON object";
  const p = payload as Record<string, unknown>;
  // TODO: add validation logic
  // Example:
  // if (typeof p["field"] !== "string" || p["field"].trim() === "")
  //   return "field is required and must be a non-empty string";
  return null;
}

async function ${handlerName}(ctx: NexusRequestContext): Promise<void> {
  const payload = await ctx.readJson();
  const err = ${validatorName}(payload);
  if (err) {
    ctx.error(400, err, "VALIDATION_ERROR");
    return;
  }

  // TODO: implement business logic
  const p = payload as Record<string, unknown>;

  ctx.json(200, {
    status: "ok",
    // TODO: return actual data
  });
}
`;

  // ── Generate the router dispatch snippet ─────────────────────────────────

  const dispatchSnippet = `
      // ${method} ${routePath}
      if (ctx.req.method === "${method}" && ctx.req.url === "${routePath}") {
        await ${handlerName}(ctx);
        return;
      }
`;

  // ── Generate the test snippet ────────────────────────────────────────────

  const testSnippet = `
  describe("${method} ${routePath}", () => {
    it("rejects empty body", async () => {
      const res = await fetch(\`\${base}${routePath}\`, {
        method: "${method}",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({}),
      });
      expect(res.status).toBe(400);
      const body = (await res.json()) as Record<string, unknown>;
      expect(body["code"]).toBe("VALIDATION_ERROR");
    });

    // TODO: add happy-path test
    // it("accepts valid payload", async () => {
    //   const res = await fetch(\`\${base}${routePath}\`, {
    //     method: "${method}",
    //     headers: { "content-type": "application/json" },
    //     body: JSON.stringify({ /* valid fields */ }),
    //   });
    //   expect(res.status).toBe(200);
    // });
  });
`;

  // ── Write files ─────────────────────────────────────────────────────────

  // 1. Write the handler to a new file: src/handlers/<name>.ts
  const handlersDir = join(appDir, "src", "handlers");
  await mkdir(handlersDir, { recursive: true });

  const handlerFile = join(handlersDir, `${name}.ts`);
  const handlerContent = `// Handler: ${method} ${routePath}
// Generated by nx-factory generate endpoint ${name}

import type { NexusRequestContext } from "@nexus/core";

type ValidationResult = string | null;

${routeSnippet}
`;

  await writeFile(handlerFile, handlerContent, "utf8");

  // 2. Append the dispatch to src/index.ts (or note where to add it)
  const indexFile = join(appDir, "src", "index.ts");
  if (existsSync(indexFile)) {
    const indexContent = readFileSync(indexFile, "utf8");

    // Check if the import is already there
    if (!indexContent.includes(`import { ${handlerName} }`)) {
      // Add import near other imports
      const importLine = `import { ${handlerName} } from "./handlers/${name}";\n`;
      const lastImportIdx = indexContent.lastIndexOf("import ");
      if (lastImportIdx >= 0) {
        const endOfLine = indexContent.indexOf("\n", lastImportIdx);
        const updated =
          indexContent.slice(0, endOfLine + 1) + importLine + indexContent.slice(endOfLine + 1);
        await writeFile(indexFile, updated, "utf8");
      } else {
        // No imports yet — prepend
        await writeFile(indexFile, importLine + indexContent, "utf8");
      }
    }

    // Add dispatch snippet before the 404 fallback
    const updatedIndex = readFileSync(indexFile, "utf8");
    if (!updatedIndex.includes(`ctx.req.url === "${routePath}"`)) {
      const dispatchMarker = "// Fallback: 404";
      const insertAt = updatedIndex.indexOf(dispatchMarker);
      if (insertAt >= 0) {
        const newContent =
          updatedIndex.slice(0, insertAt) + dispatchSnippet + updatedIndex.slice(insertAt);
        await writeFile(indexFile, newContent, "utf8");
      }
    }
  }

  // 3. Append the test skeleton
  const testDir = join(appDir, "tests");
  await mkdir(testDir, { recursive: true });
  const testFile = join(testDir, "server.test.ts");

  if (existsSync(testFile)) {
    const testContent = readFileSync(testFile, "utf8");
    if (!testContent.includes(routePath)) {
      // Find the last `});` which closes the describe block
      const lastClosing = testContent.lastIndexOf("});");
      if (lastClosing >= 0) {
        const newContent =
          testContent.slice(0, lastClosing) + testSnippet + testContent.slice(lastClosing);
        await writeFile(testFile, newContent, "utf8");
      }
    }
  } else {
    // No test file exists yet — create one with imports
    const testStub = `import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { createNexusServer } from "@nexus/core";
import type { NexusRequestContext, NexusServerHandle } from "@nexus/core";

// Import the router from your app
// import { router } from "../src/index";

async function router(ctx: NexusRequestContext): Promise<void> {
  // Your routes here
  ctx.error(404, "not found", "NOT_FOUND");
}

describe("${appName} smoke contract", () => {
  let base = "";
  let handle: NexusServerHandle;

  beforeAll(() => {
    handle = createNexusServer(router, {
      serviceName: "${appName}",
      now: () => "2026-06-10T00:00:00.000Z",
    });
    return new Promise<void>((resolve) => {
      handle.server.listen(0, "127.0.0.1", () => {
        const a = handle.server.address() as { port: number };
        base = \`http://127.0.0.1:\${a.port}\`;
        resolve();
      });
    });
  });
  afterAll(() => handle.close());

  it("GET /health returns 200 with security headers", async () => {
    const res = await fetch(\`\${base}/health\`);
    expect(res.status).toBe(200);
    expect(res.headers.get("x-content-type-options")).toBe("nosniff");
    expect(res.headers.get("x-request-id")).toBeTruthy();
    const body = (await res.json()) as Record<string, unknown>;
    expect(body["service"]).toBe("${appName}");
    expect(body["status"]).toBe("ok");
  });
${testSnippet}
});
`;
    await writeFile(testFile, testStub, "utf8");
  }

  process.stdout.write(
    JSON.stringify({
      level: "info",
      message: "endpoint generated",
      endpoint: name,
      method,
      path: routePath,
      app: appName,
      handler: `src/handlers/${name}.ts`,
    }) + "\n",
  );

  process.stderr.write(`
✅ Endpoint ${method} ${routePath} generated

Created:
  src/handlers/${name}.ts   — handler + validation
  (index.ts updated)        — route dispatch
  (tests updated)           — test stubs

TODO:
  - Fill in validation logic in ${validatorName}()
  - Implement business logic in ${handlerName}()
  - Add happy-path test
`);
}
