#!/usr/bin/env bun
/**
 * git-remote-nexus: makes verification the default path instead of an extra
 * command. With the helper installed (`forge install-helper`):
 *
 *   git clone -c nexus.trustRoot=sha256:<fingerprint> nexus::https://host/repo.git
 *   git pull / git fetch      (any remote whose URL starts with nexus::)
 *
 * Every list runs the full `forge verify` (verify.ts) and aborts the git
 * command if it fails. Fetches copy objects from the verified mirror, never
 * straight from the server, so what lands in the working repository is
 * exactly what was verified. Pushes go to the server as usual (its hook
 * checks them) after the current state has been verified.
 *
 * Trust root: $NEXUS_FORGE_TRUST_ROOT or `git config nexus.trustRoot`
 * (fingerprint or file). Token: $NEXUS_FORGE_TOKEN.
 *
 * Protocol: gitremote-helpers(7), capabilities "fetch" and "push".
 */
import { constants, accessSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { runGit } from "../backend/git/env";
import { CLIENT_GIT_CONFIG, checkUrl, clientOptions, verifyRepository } from "./verify";

/** Write the git-remote-nexus launcher into `dir`, executable, and return its path. */
export function installHelper(dir: string): string {
  mkdirSync(dir, { recursive: true });
  const target = path.join(dir, "git-remote-nexus");
  const quote = (value: string) => `'${value.split("'").join("'\\''")}'`;
  writeFileSync(
    target,
    `#!/bin/sh\n# Generated by \`forge install-helper\`.\nexec ${quote(process.execPath)} ${quote(import.meta.path)} "$@"\n`,
    { mode: 0o755 },
  );
  accessSync(target, constants.X_OK);
  return target;
}

async function run(url: string): Promise<number> {
  const checked = checkUrl(url);
  if ("error" in checked) return die(checked.error);
  const configured = await runGit(["config", "--get", "nexus.trustRoot"], { inheritEnv: true });
  const trustRoot = process.env.NEXUS_FORGE_TRUST_ROOT || configured.stdout.trim();
  const options = clientOptions();

  let mirror: string | null = null;
  const batch: string[] = [];
  for await (const line of console) {
    if (line === "capabilities") {
      await say("fetch\npush\n\n");
    } else if (line === "list" || line === "list for-push") {
      const result = await verifyRepository(checked.url, {
        ...options,
        ...(trustRoot ? { trustRoot } : {}),
      });
      if (!result.ok) return die(`verification failed: ${result.error}`);
      mirror = result.mirror;
      const head = await runGit(["symbolic-ref", "HEAD"], { cwd: mirror });
      const lines = [...result.refs].map(([ref, id]) => `${id} ${ref}`);
      const target = head.stdout.trim();
      if (result.refs.has(target)) lines.push(`@${target} HEAD`);
      await say(`${lines.join("\n")}${lines.length ? "\n" : ""}\n`);
    } else if (line.startsWith("fetch ") || line.startsWith("push ")) {
      batch.push(line);
    } else if (line === "") {
      if (batch.length === 0) return 0; // end of commands
      const commands = batch.splice(0);
      if (commands[0]?.startsWith("fetch ")) {
        if (!mirror) return die("fetch before list");
        const refs = commands.map((c) => c.split(" ")[2] ?? "");
        const fetched = await runGit(
          ["fetch", "--quiet", "--no-tags", "--no-write-fetch-head", mirror, ...refs],
          { inheritEnv: true, config: { ...CLIENT_GIT_CONFIG, "protocol.file.allow": "always" } },
        );
        if (fetched.code !== 0)
          return die(`fetch from the verified mirror failed: ${fetched.stderr}`);
        await say("\n");
      } else {
        await say(await push(checked.url, options.token, commands));
      }
    } else {
      return die(`unsupported command: ${line}`);
    }
  }
  return 0;
}

/** Push through the normal https transport; report each ref as git expects. */
async function push(url: string, token: string, commands: string[]): Promise<string> {
  const specs = commands.map((c) => c.slice("push ".length));
  const result = await runGit(["push", "--porcelain", url, ...specs], {
    inheritEnv: true,
    config: {
      ...CLIENT_GIT_CONFIG,
      ...(token ? { "http.extraHeader": `Authorization: Bearer ${token}` } : {}),
    },
  });
  if (result.stderr.trim()) process.stderr.write(result.stderr);
  const outcome = new Map<string, string>();
  for (const line of result.stdout.split("\n")) {
    const [flag, refs, summary = ""] = line.split("\t");
    const dst = refs?.split(":")[1];
    if (flag && dst) outcome.set(dst, flag === "!" ? `error ${dst} ${summary}` : `ok ${dst}`);
  }
  const lines = specs.map((spec) => {
    const dst = spec.split(":")[1] ?? "";
    return outcome.get(dst) ?? `error ${dst} push failed`;
  });
  return `${lines.join("\n")}\n\n`;
}

async function say(text: string): Promise<void> {
  await Bun.write(Bun.stdout, text);
}

function die(message: string): number {
  console.error(`nexus: ${message}`);
  return 1;
}

if (import.meta.main) {
  const url = process.argv[3] ?? process.argv[2] ?? "";
  run(url).then(
    (code) => process.exit(code),
    (error) => {
      console.error(`nexus: ${(error as Error).message}`);
      process.exit(1);
    },
  );
}
