import { constants, accessSync, mkdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

/**
 * The receive hooks git runs for every push, through core.hooksPath.
 *
 * They are generated, not checked in. git skips a hook that is not
 * executable (with only a warning), and git does not reliably carry the
 * executable bit: this repository lives on a filesystem with
 * core.fileMode=false, so checked-in scripts arrived as mode 100644 and a
 * fresh checkout would have accepted every push unchecked. Generating the
 * scripts with mode 0755 and then running them once (assertHooksRunnable)
 * turns "the hook silently did not run" into "the forge did not start".
 */
export const HOOK_NAMES = ["pre-receive", "post-receive"] as const;

const ENTRYPOINTS: Record<(typeof HOOK_NAMES)[number], string> = {
  "pre-receive": path.join(import.meta.dir, "../hooks/pre-receive.ts"),
  "post-receive": path.join(import.meta.dir, "../hooks/post-receive.ts"),
};

function shellQuote(value: string): string {
  return `'${value.split("'").join("'\\''")}'`;
}

export function installHooks(dir: string): string {
  mkdirSync(dir, { recursive: true });
  for (const name of HOOK_NAMES) {
    const script = [
      "#!/bin/sh",
      "# Generated by Nexus Forge at startup; edits are overwritten.",
      `[ "$NEXUS_FORGE_HOOK_PROBE" = 1 ] && { echo ok; exit 0; }`,
      `[ -n "$NEXUS_FORGE_BUN" ] || { echo "forge: hook environment missing; refusing" >&2; exit 1; }`,
      `exec "$NEXUS_FORGE_BUN" ${shellQuote(ENTRYPOINTS[name])}`,
      "",
    ].join("\n");
    writeFileSync(path.join(dir, name), script, { mode: 0o755 });
  }
  return dir;
}

/** Throws unless every hook is present, executable and actually runs. */
export function assertHooksRunnable(dir: string): void {
  for (const name of HOOK_NAMES) {
    const file = path.join(dir, name);
    if (!hookExecutable(file)) throw new Error(`git hook ${file} is missing or not executable`);
    const probe = Bun.spawnSync([file], {
      env: { PATH: process.env.PATH ?? "/usr/bin:/bin", NEXUS_FORGE_HOOK_PROBE: "1" },
      stdout: "pipe",
      stderr: "pipe",
    });
    if (probe.exitCode !== 0 || probe.stdout.toString().trim() !== "ok") {
      throw new Error(`git hook ${file} does not run: ${probe.stderr.toString().trim()}`);
    }
  }
}

/** Cheap per-push check that the hooks git is about to need can still run. */
export function hooksExecutable(dir: string): boolean {
  return HOOK_NAMES.every((name) => hookExecutable(path.join(dir, name)));
}

function hookExecutable(file: string): boolean {
  try {
    accessSync(file, constants.X_OK);
    return (statSync(file).mode & 0o111) !== 0;
  } catch {
    return false;
  }
}
