import { Link } from "react-router-dom";

export default function TopNav() {
  return (
    <nav className="top-nav">
      <div className="brand">
        <Link to="/">Nexus Forge</Link>
      </div>
      <div className="nav-links">
        <Link to="/">Repositories</Link>
        <Link to="/pull-requests">Pull Requests</Link>
        <Link to="/teams">Teams</Link>
        <Link to="/features">Features</Link>
        <Link to="/platform">Platform</Link>
        <Link to="/collaboration">Collab</Link>
        <Link to="/knowledge">Knowledge</Link>
        <Link to="/automation">Automation</Link>
        <Link to="/enterprise">Enterprise</Link>
        <Link to="/labs">Labs</Link>
        <Link to="/operations">Ops</Link>
        <Link to="/revenue">Revenue</Link>
        <Link to="/interop">Interop</Link>
        <Link to="/identity">Identity</Link>
        <Link to="/edge">Edge</Link>
        <Link to="/mlops">MLOps</Link>
        <Link to="/quality">Quality</Link>
        <Link to="/supply-chain">Supply Chain</Link>
        <Link to="/api-hub">API Hub</Link>
        <Link to="/chatops">ChatOps</Link>
        <Link to="/notebooks">Notebooks</Link>
        <Link to="/localization">Localization</Link>
        <Link to="/resilience">Resilience</Link>
        <Link to="/events">Events</Link>
        <Link to="/admin-console">Admin Console</Link>
        <Link to="/service-catalog">Services</Link>
        <Link to="/finops">FinOps</Link>
        <Link to="/policy-lab">Policy Lab</Link>
        <Link to="/release-engineering">Release Eng</Link>
        <Link to="/trust-center">Trust Center</Link>
        <Link to="/communications">Comms</Link>
        <Link to="/devex">DevEx</Link>
        <Link to="/legal-ops">Legal Ops</Link>
        <Link to="/secrets-vault">Secrets</Link>
        <Link to="/observability">Observability</Link>
        <Link to="/procurement">Procurement</Link>
        <Link to="/customer-success">Customer Success</Link>
        <Link to="/learning-center">Learning</Link>
        <Link to="/tenancy">Tenancy</Link>
        <Link to="/billing-core">Billing Core</Link>
        <Link to="/content-studio">Content Studio</Link>
        <Link to="/integration-exchange">Integration Exchange</Link>
        <Link to="/runtime-governance">Runtime Gov</Link>
        <Link to="/audit-intelligence">Audit Intel</Link>
        <Link to="/plugin-sandbox">Plugin Sandbox</Link>
        <Link to="/data-governance-fabric">Data Gov Fabric</Link>
        <Link to="/strategy-okr">Strategy OKR</Link>
        <Link to="/ai-safety-ops">AI Safety Ops</Link>
        <Link to="/partner-ecosystem">Partners</Link>
        <Link to="/disaster-recovery">Disaster Recovery</Link>
        <Link to="/workflow-marketplace">Workflow Market</Link>
        <Link to="/digital-twin">Digital Twin</Link>
        <Link to="/trust-analytics">Trust Analytics</Link>
        <Link to="/research-lab-ops">Research Labs</Link>
        <Link to="/experimentation-platform">Experiments</Link>
        <Link to="/platform-economics">Economics</Link>
        <Link to="/change-management-office">Change Office</Link>
        <Link to="/executive-command-center">Exec Center</Link>
        <Link to="/product-telemetry-intel">Telemetry Intel</Link>
        <Link to="/customer-journey-orchestration">Journey Ops</Link>
        <Link to="/architecture-decision-hub">ADR Hub</Link>
        <Link to="/model-marketplace-ops">Model Market</Link>
        <Link to="/infrastructure-portfolio">Infra Portfolio</Link>
        <Link to="/governance-risk-council">Gov Risk Council</Link>
        <Link to="/release-reliability-scorecards">Release Reliability</Link>
        <Link to="/enterprise-migration-factory">Migration Factory</Link>
        <Link to="/autonomous-backlog-triage">Backlog Triage</Link>
        <Link to="/cross-product-dependency-intelligence">Dependency Intel</Link>
        <Link to="/demand-forecasting-grid">Demand Forecast</Link>
        <Link to="/policy-as-code-studio">Policy Code</Link>
        <Link to="/enterprise-support-command">Support Command</Link>
        <Link to="/data-contract-registry">Data Contracts</Link>
        <Link to="/capability-maturity-radar">Maturity Radar</Link>
        <Link to="/portfolio-synergy-engine">Portfolio Synergy</Link>
        <Link to="/sovereign-cloud-ops">Sovereign Ops</Link>
        <Link to="/incident-learning-system">Incident Learning</Link>
        <Link to="/contract-testing-exchange">Contract Testing</Link>
        <Link to="/org-design-studio">Org Design</Link>
        <Link to="/platform-trust-automation">Trust Automation</Link>
        <Link to="/strategic-capacity-command">Capacity Command</Link>
        <Link to="/ecosystem-compliance-exchange">Compliance Exchange</Link>
        <Link to="/roadmap-dependency-simulator">Roadmap Simulator</Link>
        <Link to="/engineering-cognition-workspace">Eng Cognition</Link>
        <Link to="/sustainability-command-center">Sustainability</Link>
        <Link to="/api-evolution-control-tower">API Evolution</Link>
        <Link to="/developer-journey-intelligence">Dev Journey</Link>
        <Link to="/artifact-trust-chain">Artifact Trust</Link>
        <Link to="/enterprise-knowledge-graph">Knowledge Graph</Link>
        <Link to="/quantum-resilience-lab">Quantum Resilience</Link>
        <Link to="/vendor-risk-orchestration">Vendor Risk</Link>
        <Link to="/service-level-economics">Service Economics</Link>
        <Link to="/developer-credential-graph">Credential Graph</Link>
        <Link to="/autonomous-release-governor">Release Governor</Link>
        <Link to="/adaptive-compliance-orchestrator">Adaptive Compliance</Link>
        <Link to="/incident-prevention-graph">Prevention Graph</Link>
        <Link to="/cloud-cost-anomaly-lab">Cost Anomaly Lab</Link>
        <Link to="/release-cadence-optimizer">Cadence Optimizer</Link>
        <Link to="/workforce-skill-marketplace">Skill Market</Link>
        <Link to="/customer-value-observatory">Value Observatory</Link>
        <Link to="/security-chaos-engineering">Security Chaos</Link>
        <Link to="/legislative-change-radar">Legislative Radar</Link>
        <Link to="/federated-identity-assurance">Federated Identity</Link>
        <Link to="/platform-goal-cascade">Goal Cascade</Link>
        <Link to="/digital-ethics-governance">Digital Ethics</Link>
        <Link to="/supply-continuity-planner">Supply Continuity</Link>
        <Link to="/multi-cloud-failover-mesh">Failover Mesh</Link>
        <Link to="/product-experiment-ledger">Experiment Ledger</Link>
        <Link to="/stakeholder-communication-intelligence">Stakeholder Intel</Link>
        <Link to="/carbon-aware-runtime">Carbon Runtime</Link>
        <Link to="/policy-conflict-resolver">Policy Resolver</Link>
        <Link to="/globalization-readiness">Globalization</Link>
        <Link to="/dependency-remediation-ops">Dependency Ops</Link>
        <Link to="/operational-narrative-studio">Ops Narrative</Link>
        <Link to="/ai-capability-inventory">AI Capabilities</Link>
        <Link to="/supply-chain-visibility">Supply Visibility</Link>
        <Link to="/hybrid-workforce-router">Workforce Router</Link>
        <Link to="/customer-lifetime-vault">Customer LTV</Link>
        <Link to="/technical-debt-keeper">Tech Debt</Link>
        <Link to="/multi-tenant-data-isolation">Multi-Tenant Isolation</Link>
        <Link to="/product-analytics-intelligence">Product Analytics</Link>
        <Link to="/infrastructure-optimization-lab">Infra Optimization</Link>
        <Link to="/license-compliance-tracker">License Compliance</Link>
        <Link to="/cross-team-dependency-graph">Team Dependencies</Link>
        <Link to="/feature-gating-orchestrator">Feature Gating</Link>
        <Link to="/customer-data-privacy-vault">Privacy Vault</Link>
        <Link to="/workload-orchestration-engine">Workload Orchestration</Link>
        <Link to="/brand-consistency-guard">Brand Consistency</Link>
        <Link to="/performance-testing-lab">Perf Testing</Link>
        <Link to="/semantic-search-index">Semantic Search</Link>
        <Link to="/notification-orchestration">Notifications</Link>
        <Link to="/budget-allocation-engine">Budget Engine</Link>
        <Link to="/cross-cloud-orchestration">Cross-Cloud</Link>
        <Link to="/machine-translation-platform">Translation</Link>
        <Link to="/merge-strategy-engine">Merge Strategies</Link>
        <Link to="/branch-protection-policies">Branch Protection</Link>
        <Link to="/commit-signing-vault">Commit Signing</Link>
        <Link to="/code-ownership-tracker">Code Ownership</Link>
        <Link to="/cross-vcs-repository-sync">VCS Sync</Link>
        <Link to="/inventory-stub-engine">Stub Engine</Link>
        <Link to="/ci-cd-full-depth">CI/CD Depth</Link>
        <Link to="/package-registry-matrix">Registry Matrix</Link>
        <Link to="/repository-mirror-federation">Mirror Federation</Link>
        <Link to="/snippets-gists">Snippets</Link>
        <Link to="/pages-hosting">Pages</Link>
        <Link to="/issue-management-full-depth">Issue Depth</Link>
        <Link to="/project-boards-full-depth">Board Depth</Link>
        <Link to="/test-quality-management">Test Quality</Link>
        <Link to="/requirements-management">Requirements</Link>
        <Link to="/design-asset-management">Design Assets</Link>
      </div>
    </nav>
  );
}
